### ISSUE TITLE
Logik

### ISSUE THREAD

**Issue by Nik4053** [Nik4053/SchiffeVersenken#18]
@Costa-y-Bravo
@rawddy
@Flo187

**Comment by Flo187** [comment]
[LOGIK.docx](https://github.com/Nik4053/SchiffeVersenken/files/1087553/LOGIK.docx)

**Comment by rawddy** [comment]
https://www.java-forum.org/thema/schiffe-versenken-quellcode-in-methoden-umwandeln.170891/
